
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: transactions
    description: "A test model for eth"
    columns:
      - name: hash
        description: "The primary key for this table"
      - name: day
      - name: transaction_type

  - name: transactions_by_type
    description: "view of transactions data"
    columns:
      - name: trxns
      - name: transaction_type




sources:
  - name: eth
    database: bigquery-public-data
    schema: crypto_ethereum
    tables:
      - name: transactions
        description: "Raw Ethereum transactions from the public dataset"
